### ISSUE TITLE
Swing motion does not progress

### ISSUE THREAD

**Issue by Guarhide** [JH-Stephenson/Golf-Mechanics#1]
Hello! I am interested in playing golf on Roblox, so I tried running your code in the Roblox environment.
Everything else works great, but the problem is that after the PowerBar works and disappears, my character stays doing nothing while holding the golf driver.

Can you guess what could be the problem in this case?
Thanks for making a great golf program.

**Comment by SillySorcery** [comment]
Hey! Sorry for being late to get back to you on this,
 
Honestly unsure, this is quite an old project I designed a while ago, leave it with me for a week, let me see if I can find out the issue, and if I can I'll update a fix.

I've been planning to revamp these mechanics in the long-term anyway, I just haven't found time.

Thank you honestly, I'm quite surprised someone is interested in this!
James. S

**Comment by SillySorcery** [comment]
Hi, 

Update on this, I'm pretty sure it's got something to do with the animations and how they are stored within the Roblox Universe, I'm planning to update this entire codebase in the future anyway, but when I do I'll make sure you are notified about that but there's no plan for it.
